# Generated by Django 3.2.5 on 2021-08-04 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0002_alter_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
